# Automatically update dependencies.
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Disable labels on pull requests from Dependabot on GitHub.
    labels: []
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    # Disable labels on pull requests from Dependabot on GitHub.
    labels: []
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
  - package-ecosystem: 'terraform'
    directory: '/'
    # Disable labels on pull requests from Dependabot on GitHub.
    labels: []
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/'
    # Disable labels on pull requests from Dependabot on GitHub.
    labels: []
    schedule:
      interval: 'daily'
