# Automatically update dependencies.
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    labels: []
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    labels: []
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
  - package-ecosystem: 'npm'
    directory: '/frontend'
    labels: []
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    allow:
      - dependency-type: 'all'
  - package-ecosystem: 'npm'
    directory: '/e2e'
    labels: []
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
  - package-ecosystem: 'gomod'
    directory: '/backend'
    labels: []
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform'
    directory: '/deploy'
    labels: []
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/'
    labels: []
    schedule:
      interval: 'daily'
