# Automatically update dependencies.
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    rebase-strategy: 'auto'
