name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the project
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
